apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dept2-prod-workloads

resources:
- ../../argo-apps/prod/gcp-managed-prometheus-frontend
- ../../argo-apps/prod/argo-rollouts
- ../../argo-apps/prod/external-dns