#Refer to dept2-prod for an example you don't need a domain name for
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dept1-prod-workloads
resources:
  - ../../argo-apps/prod/gcp-managed-prometheus-frontend
  - ../../argo-apps/prod/argo-rollouts
  - ../../argo-apps/prod/external-dns
  - ../../argo-apps/prod/crossplane
  - ../../argo-apps/prod/argo-rollouts-demo
  - ../../argo-apps/prod/ingress-demo
  - ./www-jasonumiker-com-managed-cert

patches:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: external-dns
  patch: |-
    - op: add
      path: /spec/source/kustomize
      value:
        patches:
        - target:
            group: apps
            version: v1
            kind: Deployment
            name: external-dns
          patch: |-
            - op: add
              path: /spec/template/spec/containers/0/args/-
              value: --domain-filter=jasonumiker.com
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: ingress-demo
  patch: |-
    - op: add
      path: /spec/source/kustomize
      value:
        patches:
        - target:
            group: networking.k8s.io
            version: v1
            kind: Ingress
            name: ingress
          patch: |-
            - op: add
              path: "/metadata/annotations/networking.gke.io~1managed-certificates"
              value: "www-jasonumiker-com"
            - op: add
              path: "/metadata/annotations/external-dns.alpha.kubernetes.io~1hostname"
              value: "www.jasonumiker.com"
            - op: add
              path: "/metadata/annotations/kubernetes.io~1ingress.allow-http"
              value: "false"
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: argo-rollouts-demo
  patch: |-
    - op: add
      path: /spec/source/kustomize
      value:
        patches:
        - target:
            group: argoproj.io
            version: v1alpha1
            kind: Rollout
            name: bluegreen-demo
          patch: |-
            - op: replace
              path: /spec/strategy/blueGreen
              value:
                activeService: bluegreen-demo
                previewService: bluegreen-demo-preview
                scaleDownDelaySeconds: 300
                prePromotionAnalysis:
                  templates:
                  - templateName: success-rate
                  args:
                  - name: url_map_name
                    value: k8s2-um-0v601exe-default-bluegreen-demo-preview-20nzgdyg
                  - name: project_id
                    value: project-435400
                postPromotionAnalysis:
                  templates:
                  - templateName: success-rate
                  args:
                  - name: url_map_name
                    value: k8s2-um-0v601exe-default-bluegreen-demo-9l1rnwww
                  - name: project_id
                    value: project-435400
                previewReplicaCount: 1
                autoPromotionEnabled: true
                autoPromotionSeconds: 1
                abortScaleDownDelaySeconds: 300