apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dept1-prod-workloads
resources:
  - ../../argo-apps/prod/gcp-managed-prometheus-frontend
  - ../../argo-apps/prod/argo-rollouts
  - ../../argo-apps/prod/external-dns
  - ../../argo-apps/prod/crossplane

patches:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: external-dns
  patch: |-
    - op: add
      path: /spec/source/kustomize
      value:
        patches:
        - target:
            group: apps
            version: v1
            kind: Deployment
            name: external-dns
          patch: |-
            - op: add
              path: /spec/template/spec/containers/0/args/-
              value: --domain-filter=jasonumiker.com
