apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: capi-gke
  namespace: default
  labels:
    argoCDChart: enabled
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: GCPManagedControlPlane
    name: capi-gke-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: GCPManagedCluster
    name: capi-gke
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedCluster
metadata:
  name: capi-gke
  namespace: default
spec:
  network:
    name: default
  project: project-435400
  region: australia-southeast1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedControlPlane
metadata:
  name: capi-gke-control-plane
  namespace: default
spec:
  location: australia-southeast1
  project: project-435400
  enableAutopilot: true
  releaseChannel: stable
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: argocd
spec:
  clusterSelector:
    matchLabels:
      argoCDChart: enabled
  repoURL: https://argoproj.github.io/argo-helm
  chartName: argo-cd
  namespace: argocd
  valuesTemplate: |
    server:
      resources:
        requests:
          cpu: 50m
          memory: 72Mi
    repoServer:
      resources:
        requests:
          cpu: 50m
          memory: 72Mi
    applicationSet:
      resources:
        requests:
          cpu: 50m
          memory: 52Mi
    notifications:
      resources:
        requests:
          cpu: 50m
          memory: 52Mi
    controller:
      resources:
        requests:
          cpu: 50m
          memory: 200Mi
    dex:
      resources:
        requests:
          cpu: 50m
          memory: 62Mi
    redis:
      resources:
        requests:
          cpu: 50m
          memory: 52Mi
  options:
    waitForJobs: true
    wait: true
    timeout: 5m0s
    install:
      createNamespace: true
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: demos
spec:
  clusterSelector:
    matchLabels:
      argoCDChart: enabled
  repoURL: https://argoproj.github.io/argo-helm
  chartName: argocd-apps
  valuesTemplate: |
    applications:
      demos:
        namespace: argocd
        finalizers:
        - resources-finalizer.argocd.argoproj.io
        project: default
        sources:
          - repoURL: https://github.com/jasonumiker/gke-autopilot-capi-argocd-example.git
            path: app-manifests/ingress-demo
            targetRevision: HEAD
        destination:
          server: https://kubernetes.default.svc
          namespace: default
        syncPolicy:
          automated:
            prune: true
            selfHeal: false
  options:
    waitForJobs: true
    wait: true
    timeout: 5m0s
    install:
      createNamespace: true
