apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-demo
spec:
  project: default
  source:
    repoURL: https://github.com/jasonumiker/gke-autopilot-capi-argocd-example
    targetRevision: HEAD
    path: app-manifests/ingress-demo
    kustomize:
      patches:
      - target:
          group: networking.k8s.io
          version: v1
          kind: Ingress
          name: ingress
        patch: |-
          - op: replace
            path: "/metadata/annotations"
            value: |-
              kubernetes.io/ingress.global-static-ip-name: "gke-ingress"
              networking.gke.io/managed-certificates: "www-jasonumiker-com"
              kubernetes.io/ingress.allow-http: "false"
              kubernetes.io/ingress.class: "gce"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
