apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
spec:
  project: default
  source:
    chart: cnpg
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.22.1
    helm:
      releaseName: cloudnative-pg
      values: |
        resources:
          requests:
            cpu: 50m
            memory: 52Mi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true