apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dept1-dev-workloads

resources:
- ../../argo-apps/argo-rollouts
- ../../argo-apps/ingress-demo
- ../../argo-apps/argo-rollouts-demo
