# You can remove the patches if you don't want to have an HTTPS ingress-demo 
# or autoPromotion of argo-rollouts-demo. Otherwise you'll need to update them
# with your environment details
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dept1-dev-workloads

resources:
- ../../argo-apps/argo-rollouts
- ../../argo-apps/gcp-managed-prometheus-frontend
- ../../argo-apps/argo-rollouts-demo
- ./www-jasonumiker-com-managed-cert
- ../../argo-apps/external-dns
- ../../argo-apps/crossplane

patches:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: argo-rollouts-demo
  patch: |-
    - op: add
      path: /spec/source/kustomize
      value:
        patches:
        - target:
            group: argoproj.io
            version: v1alpha1
            kind: Rollout
            name: bluegreen-demo
          patch: |-
            - op: replace
              path: /spec/strategy/blueGreen
              value:
                activeService: bluegreen-demo
                previewService: bluegreen-demo-preview
                scaleDownDelaySeconds: 300
                prePromotionAnalysis:
                  templates:
                  - templateName: success-rate
                  args:
                  - name: url_map_name
                    value: k8s2-um-1cf9hwd1-default-bluegreen-demo-preview-cn1eress
                  - name: project_id
                    value: project-435400
                postPromotionAnalysis:
                  templates:
                  - templateName: success-rate
                  args:
                  - name: url_map_name
                    value: k8s2-um-1cf9hwd1-default-bluegreen-demo-94bd5pw1
                  - name: project_id
                    value: project-435400
                previewReplicaCount: 1
                autoPromotionEnabled: true
                autoPromotionSeconds: 1
                abortScaleDownDelaySeconds: 300
