apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: url_map_name
  - name: project_id
  metrics:
  - name: success-rate
    interval: 60s
    count: 5
    successCondition: result[0] >= 0.95
    provider:
      prometheus:
        address: http://frontend.default.svc.cluster.local:9090
        query: sum(irate(loadbalancing_googleapis_com:https_request_count{monitored_resource="https_lb_rule",url_map_name="{{args.url_map_name}}",project_id="{{args.project_id}}",response_code!="500"}[5m])) / sum(irate(loadbalancing_googleapis_com:https_request_count{monitored_resource="https_lb_rule",url_map_name="{{args.url_map_name}}",project_id="{{args.project_id}}"}[5m]))
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bluegreen-demo
  labels:
    app: bluegreen-demo
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: bluegreen-demo
  template:
    metadata:
      labels:
        app: bluegreen-demo
    spec:
      containers:
      - name: bluegreen-demo
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
  strategy:
    blueGreen:
      activeService: bluegreen-demo
      previewService: bluegreen-demo-preview
      prePromotionAnalysis:
        templates:
        - templateName: success-rate
        args:
        - name: url_map_name
          value: k8s2-um-1cf9hwd1-default-bluegreen-demo-preview-cn1eress
        - name: project_id
          value: project-435400
      postPromotionAnalysis:
        templates:
        - templateName: success-rate
        args:
        - name: url_map_name
          value: k8s2-um-1cf9hwd1-default-bluegreen-demo-94bd5pw1
        - name: project_id
          value: project-435400
      previewReplicaCount: 1
      autoPromotionEnabled: true
      autoPromotionSeconds: 1
      scaleDownDelaySeconds: 30
      abortScaleDownDelaySeconds: 30
