apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argo-rollouts-demo

resources:
- bluegreen-service.yaml
- bluegreen-ingress.yaml
- bluegreen-preview-service.yaml
- bluegreen-preview-ingress.yaml
- bluegreen-rollout-automatic.yaml
