apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- bluegreen-service.yaml
- bluegreen-ingress.yaml
- bluegreen-preview-service.yaml
- bluegreen-preview-ingress.yaml
- bluegreen-rollout-automatic.yaml
