apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demos
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: workloads/demos
    repoURL: https://github.com/jasonumiker/gke-autopilot-capi-argocd-example.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false