apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bluegreen-demo
  labels:
    app: bluegreen-demo
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: bluegreen-demo
  template:
    metadata:
      labels:
        app: bluegreen-demo
    spec:
      containers:
      - name: bluegreen-demo
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
  strategy:
    blueGreen:
      activeService: bluegreen-demo
      previewService: bluegreen-demo-preview
      prePromotionAnalysis:
        templates:
        - templateName: success-rate
        args:
        - name: url_map_name
          value: k8s2-um-1cf9hwd1-default-bluegreen-demo-preview-cn1eress
        - name: project_id
          value: project-435400
      postPromotionAnalysis:
        templates:
        - templateName: success-rate
        args:
        - name: url_map_name
          value: k8s2-um-1cf9hwd1-default-bluegreen-demo-94bd5pw1
        - name: project_id
          value: project-435400
      previewReplicaCount: 1
      autoPromotionEnabled: true
      autoPromotionSeconds: 1
      scaleDownDelaySeconds: 30
      abortScaleDownDelaySeconds: 30
